open_valve:
  name: Open Valve
  description: Opens the valve
  fields: {}

close_valve:
  name: Close Valve
  description: Closes the valve
  fields: {}

clear_alarms:
  name: Clear Alarms
  description: Clears any active alarms
  fields: {}

clear_warnings:
  name: Clear Warnings
  description: Clears any active warnings
  fields: {}

clear_notifications:
  name: Clear Notifications
  description: Clears any active notifications
  fields: {}

enable_buzzer:
  name: Enable Buzzer
  description: Enable alarm buzzer
  fields: {}

disable_buzzer:
  name: Disable Buzzer
  description: Disable alarm buzzer
  fields: {}

set_profile:
  name: Set Profile
  description: Sets the profile for the device
  fields:
    profile_number:
      name: Profile Number
      description: The profile number to set
      required: true
      selector:
        number:
          min: 1
          max: 8

microleakage_test:
  name: Microleakage test
  description: Start microleakage test
  fields: {}

microleakage_time:
  name: Set microleakage test time
  description: Set the time for the microleakage test in the format HH:MM
  fields:
    time:
      name: Time
      description: The time in HH:MM format
      required: true
      selector:
        time:

microleakage_schedule:
  name: Set microleakage test schedule
  description: Set the schedule for the microleakage test
  fields:
    schedule:
      name: Schedule
      description: The schedule for the microleakage test
      required: true
      selector:
        select:
          options:
            - label: Daily
              value: "1"
            - label: Weekly
              value: "2"
            - label: Monthly
              value: "3"

regeneration_mode:
  name: Set regeneration mode
  description: Change the regeneration mode of a NeoSoft device
  fields:
    mode:
      name: Regeneration mode
      description: Mode to set on the device
      required: true
      selector:
        select:
          options:
            - label: Standard
              value: "1"
            - label: ECO
              value: "2"
            - label: Power
              value: "3"
            - label: Automatic
              value: "4"

set_regeneration_interval:
  name: Set regeneration interval
  description: Set the interval in days between regenerations (1-3)
  fields:
    days:
      name: Days
      description: Number of days (1-3)
      required: true
      selector:
        number:
          min: 1
          max: 3
          step: 1

set_regeneration_time:
  name: Set regeneration time
  description: Set the regeneration time
  fields:
    time:
      name: Time
      description: Time of day for regeneration (HH:MM)
      required: true
      selector:
        time:

generic_service:
  name: Generic service call
  description: >
    Make a generic service call to the device. This service allows you to specify
    an endpoint and data to send to the device. Use this for custom commands
    that are not covered by other services
  fields:
    endpoint:
      name: Endpoint
      description: >
        The endpoint to call on the device. This should be a valid endpoint
        supported by the device (e.g., "set/some_endpoint")
      required: true
      example: "some_endpoint"
      selector:
        text:
    data:
      name: Data
      description: >
        The data to send with the request. This can be a number, string, time,
        name, or any other text-based input, depending on the endpoint
      required: true
      example: "example_data"
      selector:
        text: